### ISSUE TITLE
element insert issue

### ISSUE THREAD

**Issue by cy3486** [pschlupnzl/lasercanvas-web#8]
Element unable to be inserted between M1 and M3, in the ring resonator

![Screenshot 2023-03-15 111326](https://user-images.githubusercontent.com/37792034/225196801-7b98caa7-68b8-4f36-97a7-00c09920ee60.png)

**Comment by pschlupnzl** [comment]
This has been resolved by [PR#9](https://github.com/pschlupnzl/lasercanvas-web/pull/9)

The last leg of a ring cavity is calculated automatically to close the ring, so some actions (e.g. variables or element deletions) can place the system in a non-physical state. If this happens, dragging the remaining optics will restore the cavity when the geometry becomes valid again.
